### ISSUE TITLE
from model import Attention, GatedAttention

### ISSUE THREAD

**Issue by douxWh** [hrlblab/CS-MIL#1]
Dear @hrlalab ,
Could you please provide the script file,model.py,if convenient.
Thank you.

**Comment by ddrrnn123** [comment]
We have uploaded model.py for the baseline Attention, GatedAttention networks. 
For training:
`python MIL_main_DeepSurv_batch_Stage1_stack.py`
For testing:
`python MIL_global_Stage1_Testing_all.py`

You man change the roots in those python files to load your data and save the outcome in your local foloders.

We will provide more detailed introduction to use or develop the model soon. Thanks!
