### ISSUE TITLE
Replicating primary training pipeline

### ISSUE THREAD

**Issue by samgriesemer** [hrlblab/CS-MIL#2]
Hello,

As mentioned in #1, `MIL_main_DeepSurv_batch_Stage1_stack.py` seems to be the main training entry point. However, there are a number of files needed to instantiate the data loaders (e.g. lines 194-195) that have been difficult to track down. Can you point us to the right sources for finding the files needed to run the main training loop on the (publicly available) datasets used in the paper?

It's overall just a little unclear which dataloaders are meant to be used with which datasets, and from which existing works dataset files should be acquired in order to replicate the intended data setup. Any help clearing this up would be much appreciated!

**Comment by ddrrnn123** [comment]
Hi Sam!

Currently, the journal version of the paper is under review. We will release detailed instructions and code for the entire pipeline after the paper is accepted. At this time, you may refer to the model architecture of CS-MIL and the training settings in  `DeepAttnMISL_model_CSMIL.py` and `MIL_main_DeepSurv_batch_Stage1_stack.py`.

Please let me know if you have any further questions!

Best,
Ruining
