### ISSUE TITLE
I have some doubts. What code is FFN embodied in

### ISSUE THREAD

**Issue by 464hee** [hrlblab/CS-MIL#4]
![image](https://github.com/hrlblab/CS-MIL/assets/100740023/315a4ce7-870c-4de5-ac91-0cc9fa1e7d61)

**Comment by 464hee** [comment]
@ddrrnn123 @hrlblab

**Comment by ddrrnn123** [comment]
Hi! In the latest version of the manuscript, we clarify that the encoder for sequencing data is an SNN. You may follow the architecture and code in the PORPOISE pipeline.

https://github.com/mahmoodlab/PORPOISE/blob/master/models/model_genomic.py

Please let me know if you have any further questions!

Best,
Ruining
