### ISSUE TITLE
Replicate the training process of the Toydataset.

### ISSUE THREAD

**Issue by tizikaoroubanfan** [hrlblab/CS-MIL#5]
Hello author, I have some questions about the Toydataset that I would like to ask you. I want to train on this dataset, but there are multiple folders provided in your dataset, and I would like to know which specific data files are used for training.

**Comment by ddrrnn123** [comment]
The exact training set is dataset1_train_label and dataset2_train_label. We select the best epoch according to dataset1_val_label and dataset2_val_label. Please let us know if you have any questions!

Best,
Ruining

**Comment by tizikaoroubanfan** [comment]
Thank you very much for your answer
